# Generated by Django 2.1.5 on 2019-01-19 23:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pri_arena', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arena',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
