# Generated by Django 2.1.5 on 2019-01-19 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pri_arena', '0002_arena_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='arena',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
